language: generic

services: docker

script:
  - set -e
  - set -o pipefail
  - IMAGE_NAME=quay.io/theassassin/fgallery
  - IMAGE_TAG=latest
  - IMAGE="$IMAGE_NAME":"$IMAGE_TAG"
  - docker pull "$IMAGE"
  - docker build --cache-from "$IMAGE" -t "$IMAGE" .

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin quay.io
  - docker push "$IMAGE"
