language: generic

services: docker

script:
  - set -e
  - set -o pipefail
  - IMAGE_NAME=theassassin/fgallery
  - docker build -t "$IMAGE_NAME":latest .

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin quay.io
  - docker push "$IMAGE_NAME":latest
